// <auto-generated />
namespace SmartRP.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddApprovedNOInGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddApprovedNOInGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201803101041396_AddApprovedNOInGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
