// <auto-generated />
namespace SmartRP.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddSupervisorTypeInSupervisor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSupervisorTypeInSupervisor));
        
        string IMigrationMetadata.Id
        {
            get { return "201803090726596_AddSupervisorTypeInSupervisor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
