/*
   Step 2:

   Add all types of users in Table: Supervisor, CoSupervisor, ExternalSupervisor, CoOrdinator, Student.

*/


INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (2, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (3, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (4, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (5, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (6, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (7, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (8, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (9, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (10, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (11, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (12, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (13, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (14, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (15, 1)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (16, 1)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (17, 1)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (18, 1)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (19, 1)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (20, 1)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (21, 2)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (22, 1)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (23, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (26, 1)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (34, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (35, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (42, 1)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (58, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (59, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (61, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (63, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (64, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (65, 1)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (66, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (87, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (90, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (99, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (103, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (116, 1)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (120, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (125, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (129, 0)
INSERT [dbo].[Supervisor] ([ID], [SupervisorType]) VALUES (130, 0)
INSERT [dbo].[CoSupervisor] ([ID], [MySupervisorID]) VALUES (15, 0)
INSERT [dbo].[CoSupervisor] ([ID], [MySupervisorID]) VALUES (16, 2)
INSERT [dbo].[CoSupervisor] ([ID], [MySupervisorID]) VALUES (17, 0)
INSERT [dbo].[CoSupervisor] ([ID], [MySupervisorID]) VALUES (18, 0)
INSERT [dbo].[CoSupervisor] ([ID], [MySupervisorID]) VALUES (19, 2)
INSERT [dbo].[CoSupervisor] ([ID], [MySupervisorID]) VALUES (20, 0)
INSERT [dbo].[CoSupervisor] ([ID], [MySupervisorID]) VALUES (22, 23)
INSERT [dbo].[CoSupervisor] ([ID], [MySupervisorID]) VALUES (26, 11)
INSERT [dbo].[CoSupervisor] ([ID], [MySupervisorID]) VALUES (42, 0)
INSERT [dbo].[CoSupervisor] ([ID], [MySupervisorID]) VALUES (65, 2)
INSERT [dbo].[CoSupervisor] ([ID], [MySupervisorID]) VALUES (116, 4)
INSERT [dbo].[ExternalSupervisor] ([ID], [MySupervisorID]) VALUES (21, 0)
INSERT [dbo].[Coordinator] ([ID]) VALUES (1)
INSERT [dbo].[Coordinator] ([ID]) VALUES (24)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (25, N'66666666', N'MIT', NULL, NULL, 0, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (27, N'12461784', N'Masters in IT (Data Analytics)', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (28, N'12110096', N'Master', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (29, N'12716332', N'Postgraduate', NULL, 3.38, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (30, N'12207561', N'master ', NULL, 2.71, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (31, N'12520146', N'bachelor of computer science', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (32, N'12478501', N'Master of IT', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (33, N'00000000', N'MIT', NULL, NULL, 0, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (36, N'12448801', N'Bachelor', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (37, N'12716193', N'IT Master in Second Year', NULL, 2.94, 0, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (38, N'12654644', N'Bachelors', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (39, N'12688572', N'Masters of Science in internetworking ', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (40, N'12674990', N'BS in Computer Engineer ', NULL, NULL, 0, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (41, N'12427389', N'Masters', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (43, NULL, NULL, NULL, NULL, 0, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (44, N'12431476', N'Master of Science in Internetworking', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (45, N'12481747', N'master', NULL, 3.3, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (46, N'11201973', N'B - Computer Science', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (47, N'12167247', N'Master in IT', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (48, N'12861896', N'Bachelor of Science', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (49, N'12515399', N'Bachelor of Science (Computer Science)', NULL, 2.4, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (50, N'12767176', N'BBA IT(honors)', NULL, 8.3, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (51, N'12669267', N'Master''s in IT', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (52, N'12511147', N'Masters in IT(2016-)', NULL, 2.67, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (53, N'12658276', N'Master of IT', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (54, N'12646865', N'Bachelor', NULL, 3.5, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (55, NULL, NULL, NULL, NULL, 0, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (56, N'12411411', N'Bachelor of Fine and Applied arts', NULL, 3.66, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (57, N'12437923', N'Master in Information Technology', NULL, NULL, 0, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (60, N'12765501', N'Bachelor', NULL, 3.06, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (62, N'12642171', N'Master', NULL, 2.7, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (67, N'12755334', N'Master', NULL, 3.59, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (68, N'12444345', N'Bachelors of Technology (CS)', NULL, 3.3, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (69, N'12444372', N'Bachelors of Technology', NULL, 3.3, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (70, N'12214639', N'Bachelor', NULL, 41.5, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (71, N'12716508', N'Bachelors of technology in  computer science ', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (72, N'12435261', N'bachelor', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (73, N'12489391', N'bachelor', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (74, N'12740585', N'Bachelors of Engineering Information Technology ', NULL, 3, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (75, N'12514182', N'Bachelor', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (76, N'99186227', N'Master of IT', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (77, N'12738290', N'Bachelor of Technology ', NULL, 3, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (78, N'12645711', N'bachelor of interactive media', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (79, N'12521581', N'Master', NULL, 2.8, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (80, N'12520932', N'Master', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (81, N'99183954', N'Master of science in internetworking ', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (82, N'12210706', N'Master of IT', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (83, N'12638425', N'Master of science in Internetworking', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (84, N'99174017', N'masters', NULL, 2, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (85, N'12786366', N'Bachelor degree', NULL, 3.5, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (86, N'12445755', N'Master of information technology ', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (88, N'12483703', N'Master of IT', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (89, N'12711596', N'B.Tech', NULL, 8, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (91, N'12523989', N'bachelor in computer application', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (92, N'12676553', N'Masters of Science (Internetworking)', NULL, 3.8, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (93, N'12409835', N'Master', NULL, 2.88, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (94, N'12652727', N'Master of Information Tecchnology', NULL, 2.96, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (95, N'12192860', N'Postgraduate', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (96, N'13005424', N'BSc', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (97, N'12695944', N'Master of IT', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (98, N'12448849', N'IT of Master', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (100, N'99197802', N'Masters of Information technology', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (101, N'12080990', N'master of information technology(extension)', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (102, N'11579529', N'MIT', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (104, N'12646269', N'master', NULL, 3, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (105, N'11965062', N'Master', NULL, NULL, 0, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (106, N'99186746', N'Bachelor', NULL, 3.1, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (107, N'12674990', N'Masters in IT', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (108, N'12409177', N'Bachelor', NULL, 2, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (109, N'12738403', N'Master', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (110, N'12629186', N'Master of IT', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (111, N'12455251', N'master', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (112, N'12475707', N'Master of IT', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (113, N'12413415', N'Bachelors in IT', NULL, 3.5, 0, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (114, N'12437923', N'Master in Information Technology', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (115, N'12485064', N'Master', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (117, N'12507873', N'Master of Science in Internetworking', NULL, NULL, 0, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (118, N'12194914', N'MIT', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (119, N'99172001', N'Bachelor of IT ', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (121, N'99189021', N'Master', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (122, N'12123838', N'bechelor', NULL, 2, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (124, NULL, NULL, NULL, NULL, 0, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (126, NULL, NULL, NULL, NULL, 0, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (127, N'12695944', N'Graduate', NULL, NULL, 1, NULL)
INSERT [dbo].[Student] ([ID], [StudentID], [Degree], [PhotoURL], [GPA], [HasJoinedCurrentSubjectProjectGroup], [PreProjectID]) VALUES (128, N'99186227', N'Master of IT', NULL, NULL, 1, NULL)
