
 /*
    The Step 4:

		Add project in Table ProjectPool

*/

SET IDENTITY_INSERT [dbo].[ProjectPool] ON 

INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (1, N'Immersive Visualisation for Big Data Insights', N'Aims and Objectives: 
Develop an immersive (VR) visualisation of big data that:
* Accelerates insight for domain experts
* Provide insights for non-domain experts
* Highlights the unexpected, i.e. insights impossible to achieve through other means

Outcomes:
* A documented method for a customer to take multiple data sets and visualise these in VR and/or the Data Arena
* A presentation of the techniques explored, discarded, adopted, and the learnings of the project
* A demonstration of the achieved data visualisation in the Data Arena
 
Requirements:
* Working knowledge of Python
* Working knowledge or keenness to learn SCRUM
* Working knowledge or keenness to learn data visualisation techniques
* Disciplined work ethic to commit x hours per week, working with industry and federal government partners
* Sensitivity in handling confidential information
* Ability to learn quickly in high pressure, and often ambiguous environment
* Good sense of humour', NULL, 3, CAST(N'2017-08-21T22:47:52.000' AS DateTime), CAST(N'2018-03-22T07:21:31.257' AS DateTime), 2, NULL)
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (2, N'Comparison of three advanced pathfinding algorithms for multi-robots to pick up items in a warehouse', N'The project aims to review the most advanced pathfinding algorithms for multi-robots to deliver items from given source locations to target locations in a warehouse. There are two levels, one level is for single robot and the second level is for multiple robots.
The warehouse is modelled as a 2D grid. A robot can only move through the grid cells (no diagonal path is allowed).
The performance of an algorithm is measured by the time spent or the steps needed to deliver an item from a specific location to the target location.

Objectives:
-	Conduct a literature review on pathfinding algorithms for multi-robots to find optimal paths to deliver items from given source locations to target locations
-	Identify three of the most advanced pathfinding algorithms
-	Get the selected algorithms working (can use the existing implementations)
-	Apply these algorithms to a given floor configuration of a warehouse (one 2D grid with N x M cells, N and M is the number of rows and columns in the grid, respectively) 
-	Integrate a simple collision avoidance idea in the algorithms
-	Compare the performance of these algorithms
', N'~/Resources/projectpool/9fd4b6e2-c87d-4246-8efc-d4c783a184f6-lh-2-identify and im.docx', 3, CAST(N'2017-07-28T11:10:24.000' AS DateTime), CAST(N'2018-03-22T07:16:09.693' AS DateTime), 2, N'Understanding computer programs written in a higher level of programming language, such as Python, java or C++')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (3, N'Advanced Nearest Neighbour Searching', N'Near neighbour searching this the task of finding close matches to a query vector in a large database of vectors. A naive approach to solving the task is to compute the distance between each data base vector and the query vector, returning records where the distance is small. For large databases and high dimensional vectors, this approach is often not sufficient. Many methods are proposed to perform fast, but approximate, near neighbour matching.
Project objectives:
The focus of this project is to examine methods for performing efficient and accurate near neighbour searching in high dimensional Euclidean spaces. In particular, the project to bring together state of the art research on locality sensitive hashing.
Expected outcomes/deliverables:
 
?	A comprehensive research report (about 8,000-10,000 words), or
?	A finished research article to a peer-refereed academic journal or conference
', N'~/Resources/projectpool/008fa7da-1d52-44bb-8a78-7fa3214128ff-bd-1-advanced-near.docx', 2, CAST(N'2017-07-28T07:54:56.673' AS DateTime), CAST(N'2017-07-28T07:54:56.673' AS DateTime), 3, NULL)
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (4, N'Statistical Machine Learning for Genetic Data', N'Background/Introduction:
A SNP (single nucleotide polymorphism) is a DNA sequence variation occurring when a single building block of DNA (a nucleotide); either adenine (A), thymine (T), cytosine (C), or guanine (G) differs between members of a species. Selected SNPs can explain the differences between individuals in various traits, such as eye, skin and hair colour as well as facial appearance.
Recent work has identified 34 SNPs in 26 genomic regions strongly associated with 8 craniofacial traits. That work resulted in a dataset of records from 587 individuals. Each record has the value of 3300 SNPs and visual features of an individual. Visual features include 94 facial structure measurements and 10 other traits such as skin pigmentation and ancestry.
Project objectives:
The aim of this project is to apply techniques from statistical machine learning to the described dataset with a view to identifying associations between SNP data and visual features. The project includes (i) developing data pre-processing techniques to get the most from statistical machine learning, (ii) conducting machine learning experiments, and (iii) reporting on findings.
Expected outcomes/deliverables:
?	A comprehensive research report (about 8,000-10,000 words), or
?	A finished research article to a peer-refereed academic journal or conference
Required skills/knowledge/academic merit:
?	Should be willing to write Python, R or Matlab code and be familiar with common machine learning techniques.
?	The students must be familiar with, or be self-motivated to learn, statistical machine learning (supervision provided).
?	Writing skills.
 
', N'~/Resources/projectpool/39173160-c92c-4357-ac98-a7bf001b30e0-bd-2-statistical-m.docx', 2, CAST(N'2017-07-28T08:08:55.957' AS DateTime), CAST(N'2017-07-28T08:10:15.273' AS DateTime), 3, NULL)
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (5, N'Feature drift in new product development', N'Consider yourselves as a developer of a mobile phone. Your objective is to find out what novel features can be added in the mobile phone’s next iteration by which you can increase your customer base and profits. Feature drift assists you in achieving this aim by first identifying products that are related or similar to mobile phone and then determine what new features from them can be imported to the mobile phone in its next iteration. In other words, feature drift assists product developers to identify novel features that can be added to a reference product (mobile phone) from related products (for example camera). Figure 1 shows the working of feature drift. The blue circle represents the features of a mobile phone while the orange circle represents the features of a camera. The intersection of these two circles represents the common features between these products. The features highlighted in red are considered as features that are unique to camera that can be drifted into the mobile phone’s camera in its next iteration. ', N'~/Resources/projectpool/98daa5af-68b4-465b-afb7-b3c6ce981c9f-fh-1 feature drift i.docx', 3, CAST(N'2017-07-28T08:25:13.377' AS DateTime), CAST(N'2017-07-28T08:25:13.377' AS DateTime), 4, NULL)
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (7, N'Games and System Modelling for Designing Sustainable Futures', N'This project lies at the intersection of environmental awareness, systems dynamics and games for education and is co-supervised by the School of Software (SOS) and the School of Systems, Management and Leadership (SML). This project involves producing a model of real-world resource production and consumption and embedding that model in a game design that encourages players to consider the impact of the various resource utilization choices on the sustainability of the environment. This project has a wide scope for innovative research and creative thinking across the modelling system dynamics, game design, game development, and user analysis. Depending on the group''s competencies and past experiences, one or more of these stages of the project can be chosen, with a development deliverable taking the form of a console, desktop GUI, web, or 2D/3D game application.', NULL, 3, CAST(N'2017-08-10T23:15:15.773' AS DateTime), CAST(N'2017-08-10T23:56:29.917' AS DateTime), 8, NULL)
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (8, N'QoS assessment in cloud for forming an SLA', N'Cloud computing is an emerging technology that have a broad scope to offers a wide range of services to revolutionize the existing IT infrastructure. This internet based technology offers a services like – on demand service, shared resources, multi-tenant architecture, scalability, portability, elasticity and giving an illusion of having an infinite resource by a consumer through virtualization. Because of the elastic nature of a cloud it is very critical of a service provider specially for a small/medium cloud provider to form a viable SLA with a consumer to avoid any service violation. SLA is a key agreement that need to be intelligently form and monitor, and if there is a chance of service violation then a provider should be informed to take necessary remedial action to avoid violation.', N'~/Resources/projectpool/6fb25c35-b6d8-4e7b-adf5-2ece6ea2d69b-first.docx', 3, CAST(N'2017-07-27T20:49:35.623' AS DateTime), CAST(N'2017-07-27T20:49:35.623' AS DateTime), 19, NULL)
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (9, N'Ontology based Quality of Service (QoS) assessment in cloud', N'Defining the QoS of cloud services is the key factor for both service providers and service consumers when they are forming their SLAs. Heterogeneity of service descriptions, however, often hinders the aggregation of QoS parameters. The ontology based QoS aggregation which integrates the semantics of QoS parameters and then aggregates it which would help them to form a long term relationship and enable them to form a viable SLA. ', NULL, 3, CAST(N'2017-07-27T20:51:57.783' AS DateTime), CAST(N'2017-07-27T20:51:57.783' AS DateTime), 19, NULL)
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (10, N'Forming a viable SLA in cloud by service provider', N'Cloud computing is an emerging technology that have a broad scope to offers a wide range of services to revolutionize the existing IT infrastructure. This internet based technology offers a services like – on demand service, shared resources, multitenant architecture, scalability, portability, elasticity and giving an illusion of having an infinite resource by a consumer through virtualization. Because of the elastic nature of a cloud it is very critical of a service provider specially for a small/medium cloud provider to form a viable SLA with a consumer to avoid any service violation. SLA is a key agreement that need to be intelligently form and monitor, and if there is a chance of service violation then a provider should be informed to take necessary remedial action to avoid violation.', NULL, 3, CAST(N'2017-07-27T20:55:20.280' AS DateTime), CAST(N'2017-07-27T20:55:20.280' AS DateTime), 19, NULL)
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (11, N'Design and Develop an Online Application for Retail', N'Design and Implement a Online Application for Retail. For Example, a computer retail to sale different brand , such as Dell, Hp, and Apple products, eg. desktop, laptop, and accessories. The online application can support Recommendation methods, key word search methods, Visualization of order processing, and with online payment methods, such as by paypal. The challenge issues are increased demand, a low-cost route to global market and cost reduction of promotion and sales, and delivery. 

Application can be tested on host sever.', NULL, 3, CAST(N'2017-07-31T10:07:04.000' AS DateTime), CAST(N'2018-03-23T22:08:06.943' AS DateTime), 16, NULL)
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (12, N'Statistical Analysis of Solar Energy data of different cities in Australia.', N'Project objectives: The aim of this research is to compare maximum PV output power (Solar energy) fluctuation between different cities of Australia, in order to develop effective measures to manage variability at different level of penetration for Distribution Network Service Providers. 
Expected outcomes/deliverables:
? A Research report (about 8,000-10,000 words), or 
? A finished research article to publish in Journal /Conference. 
Skills/Knowledge/Academic merit: 
-	Knowledge in mathematics and statistics is required but not mandatory (Supervision Provided). 
-	Minor Knowledge in R   is required to analyse more than 100 stations data (Minor editing is required and Supervision Provided).
-	Writing skill. ', N'~/Resources/projectpool/91fb2e98-0498-43b8-af51-ecdfa1e564ec-statisticalanalysis.pdf', 3, CAST(N'2017-07-31T22:30:47.430' AS DateTime), CAST(N'2017-08-15T03:08:49.580' AS DateTime), 15, NULL)
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (13, N'Develop a business model for community based electrification project in the context of developing countries. ', N'Project objectives: The aim of this project is to develop a business model for different kinds of users (generation and demand) of a community in order to electrify all of them. This business model will benefit both sellers who will sell their excess energy and consumer who can electrify themselves. 
Expected outcomes/deliverables:
? A Research report (about 8,000-10,000 words), or 
? A finished research article to publish in Journal /Conference. 
Skills/Knowledge/Academic merit: 
-	Knowledge in Business/Economic studies is required. 
-	Writing skill. 
', N'~/Resources/projectpool/07d2fe69-5968-4241-af8c-14e0e93b9e57-developabusinessm.pdf', 3, CAST(N'2017-07-31T22:34:41.677' AS DateTime), CAST(N'2017-08-01T13:43:22.210' AS DateTime), 15, NULL)
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (14, N'Challenges and Solutions of Supervisory Control and Data Acquisition (SCADA) system against Cyber Attacks.', N'SCADA system follows data acquisition, data communication, data representation and monitoring as well as control parameters to complete assigned task for an application. Application of SCADA system – Power generation, transmission and distribution; water distribution and reservoir system; Public buildings like electrical heating and cooling system and traffic light control system. If any of this application’s SCADA system is tempered by theft; such as water, power and traffic light control system could shut down services for thousands or millions of people.
Project objectives: The aim of this project is to identify challenges of SCADA system, possible occurrence due to cyber-attacks and propose solutions to overcome those challenges. 
Expected outcomes/deliverables:
? A Research report (about 8,000-10,000 words), or 
? A finished research article to publish in Journal /Conference. 
Skills/Knowledge/Academic merit: 
-	Knowledge in ICT is required. 
-	Writing skill. 
', N'~/Resources/projectpool/9e00ecfa-092f-4056-8d64-aaa7c4817468-challengesandsolut.pdf', 3, CAST(N'2017-07-31T23:36:03.210' AS DateTime), CAST(N'2017-08-01T13:44:02.183' AS DateTime), 15, NULL)
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (15, N'Mining students solutions to the programming exercises for knowledge discovery', N'Success and failure in introductory programming courses has intrigued researchers and educators for decades. Studies on retention posit that, on average, one third of students in an introductory programming course either withdraw or fail. In this project, a collection of students solution to the assignments of an introductory programming module will be analyzed. The project includes three main phases including a) Data extraction and transformation, b) Data analysis in a text mining framework, and c) mining the data in order to identify common response patterns in their answers.', NULL, 2, CAST(N'2017-08-24T11:53:23.707' AS DateTime), CAST(N'2017-08-24T11:53:23.707' AS DateTime), 18, NULL)
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (16, N'Prediction of students course outcome using machine learning', N'It has always been the computer science researcher''s interest to determine poor performing students at the early stages of the semester. Identification of these students helps the instructors and the lectures of the programming course to consider specific plans for the students who might be in need of assistance. In this project, students attempts in completing a set of programming exercises will be analyzed to identify present patterns which explain students engagement with the course and its relationship with the course outcome in an introductory programming module. This project will be carried in two main phases including a) collecting, transforming, and storing students attempts into a relational database, and b) performing machine learning tasks for pattern recognition purposes.', NULL, 3, CAST(N'2017-08-24T12:02:16.973' AS DateTime), CAST(N'2017-08-24T12:02:16.973' AS DateTime), 18, NULL)
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (17, N'visualising patient journeys though the health system', N'Epidemiologist are skilled at producing descriptive statistics that aid understanding the prevalence and incidence of disease ad a function of many important factors. In the same way, health systems analysts use descriptive statistics that aid understanding for how health services and resources are used. This can be used to inform policy and programs for running a state’s health system.

This approach is fine when the events of interest are taken to be independent. It is harder to gain insight for more complicated scenarios. For example patients with chronic conditions access multiple health services in complex ways. This realisation is driving initiatives such as “Health Care Homes” and “Integrated Care.” The challenge is how to use and present health system data in ways that gives statistical insight not into individual service events, but into patient’s journeys.

NSW Ministry of Health has access to data from hospital admissions, emergency department presentations, and general practice visits. These datasets are linked such that the events for individuals are grouped.

The aim of the project is to explore ways to use and present data available to NSW Ministry of Health to gain statistical insight into the journeys of patients with chronic conditions.
', N'~/Resources/projectpool/b76168c4-7fdf-4159-8645-11e917b907af-researchprojectdes.docx', 2, CAST(N'2018-03-11T23:57:58.000' AS DateTime), CAST(N'2018-03-22T05:19:28.113' AS DateTime), 3, N'Be familiar with a data visualisation software framework.
Be familiar with common data visualisation techniques.
Good English speaking and writing skills.')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (18, N'Real-time marine animal surveillance and population estimation from aerial imagery- phase 2 ', N'A real-time marine animal detection and surveying system has to be developed using the latest advances in Deep Learning. The system will detect different marine animals from image/videos captured using Unmanned Aerial Vehicles near beaches and other areas of interest. The system will be also used for aerial surveillance and estimating population of various marine animals, particularly endangered species, to facilitate the development of appropriate conservation strategies. Government agencies and other organizations responsible for aerial surveillance and saving lives on our beaches are the potential users of the project outcomes.
This is the second phase of the project. Methods for object tracking and fine tuning of detection results has to be implemented.', N'~/Resources/projectpool/8055b993-d76e-4f69-9b66-dcdbcf4ead92-projectdescription-.docx', 2, CAST(N'2018-03-18T23:50:08.000' AS DateTime), CAST(N'2018-03-18T23:50:08.000' AS DateTime), 58, N'Python, basic of machine learning, image processing, keen to learn the required skills is desirable ')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (19, N'When the internet of things meets classrooms', N'Tracking the location of the teacher or the students in the classroom may provide new insights about key events such as the provision of feedback, communication patterns, or the identification of inactive students. The aim of in this project is to build and validate an approach for automatically capturing traces of teacher’s activity in the classroom, and understand how analytics techniques can be used to visualise teacher’s mobility patterns. The particular objective is to help teachers understand their own personal mobility patterns in the classroom during lectures, workshops or any other face-to-face activity. The student will continue developing a teacher’s web app that will be tracked using indoor localisation beacons during a classroom session. The student will continue developing a teacher’s web app that to track teacher''s activity using indoor localisation beacons during a classroom session. If you are interested in developing the hardware we are also open for suggestions.', N'~/Resources/projectpool/c23aa11a-d0ce-4e06-88ef-a7c74b032fe3-cicprojectproposal.pdf', 2, CAST(N'2018-03-20T01:03:00.000' AS DateTime), CAST(N'2018-03-20T01:03:00.000' AS DateTime), 64, N'Javascript programming')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (20, N'Implement new data visualization UI', N'I have an ongoing project that is developing an new data interrogation tool specifically targeting hospital data. The software uses AngularJS, d3, and Grails. We have a challenge for how to allow an end-user to break down a plot of their data based on categorical variables. The goal of the project is to implement a design, possibly enhancing the design, so that the effectiveness of the design can be evaluated. Thus the output is a proof of concept.', NULL, 2, CAST(N'2018-03-22T05:05:50.000' AS DateTime), CAST(N'2018-03-22T05:13:02.847' AS DateTime), 3, N'Front-end and back-end web programming using the technologies mentioned in the description.')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (21, N'blockchain-based smart contracts', N'This project will explore the ways to construct smart contracts using blockchain technology.
The expected outcome is a working blockchain that supports smart contracts.', NULL, 3, CAST(N'2018-03-22T07:26:39.000' AS DateTime), CAST(N'2018-03-22T07:30:09.907' AS DateTime), 2, N'good understanding of data structure and reasonable programming skills')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (22, N'Blockchain-based asset management system', N'This project aims to explore the ways of building an asset management system using the blockchain technology. The expected outcomes are:
(i) Good understanding of blockchain technology and
(ii) A working prototype of blockchain-enabled diamond management system. ', NULL, 3, CAST(N'2018-03-22T07:30:14.000' AS DateTime), CAST(N'2018-03-22T07:57:43.647' AS DateTime), 2, N'good understanding of data structures and reasonable level of programming skills.')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (23, N'Online submission system using blockchain technology', N'This project aims to propose a new way to authenticate online submissions using the blockchain technology. 
The expected outcomes are good understanding of blockchain technology and a working prototype of  online document submission system which ensures the submissions are genuine.', NULL, 3, CAST(N'2018-03-22T07:34:35.000' AS DateTime), CAST(N'2018-03-22T07:34:35.000' AS DateTime), 2, N'good understanding of data structured and reasonable level of programming skills.')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (24, N'A blockchain - based energy consumption recording system', N'This project aims to explore a better way to record energy consumption which can prevent users'' privacy through the blockchaim technology.
The expected outcomes are good understanding of blockchain technology and a working prototype of blockchain-enabled energy consumption recording system. ', NULL, 3, CAST(N'2018-03-22T07:49:30.000' AS DateTime), CAST(N'2018-03-22T07:49:30.000' AS DateTime), 2, N'Good understanding of data structures and reasonable level of programming skills.')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (25, N'Visualisation of Passenger and Train Motions in Data Arena', N'Design and Implement a Visualization of passenger motions and train events for the data arena. An existing project is already extracting passenger location / motion as well as the train specific information along Sydney''s Town Hall train station. In order to appreciate the density of passengers and events a visualization in the data arena is sought. Implementation leveraging ogre, testing in data arena. Will need to (or already have) knowledge of Ogre (to use rag dolls).', NULL, 3, CAST(N'2018-03-22T23:29:56.000' AS DateTime), CAST(N'2018-03-22T23:43:07.633' AS DateTime), 66, N'Linux, Knowledge of C++ and/or Python needed')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (26, N'Bibliometric Information Retrieval and Representation_UTS students project', N'Please see the attached file', N'~/Resources/projectpool/95ca7fcb-37eb-4458-b5b1-9968405f4620-bibliometricinforma.docx', 3, CAST(N'2018-03-24T05:17:19.000' AS DateTime), CAST(N'2018-03-24T05:20:10.213' AS DateTime), 4, N'JAVA, JavaScript, Python, Django framework or others.')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (27, N'Information Retrieval and Representation from Discussion Forums and Chats  ', N'A discussion forum, or message board, is an online discussion site where people can hold conversations in the form of posted messages.[1] They differ from chat rooms in that messages are often longer than one line of text, and are at least temporarily archived. Also, depending on the access level of a user or the forum set-up, a posted message might need to be approved by a moderator before it becomes visible.
A discussion forum is hierarchical or tree-like in structure: a forum can contain number of sub-forums, each of which may have several topics. Within a forum''s topic, each new discussion started is called a thread, and can be replied to by as many people as so wish.

For further information about the project please see attached', N'~/Resources/projectpool/947218b0-834a-4728-9ad8-e30e1daa5150-informationretrieva.docx', 3, CAST(N'2018-03-24T05:21:42.000' AS DateTime), CAST(N'2018-03-24T05:21:42.000' AS DateTime), 4, N'Python, NLP, NLTK platform, JavaScript, Vis.js, D3.js, C# or others.')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (28, N'Cloud Software Defined Security with OpenStack', N'Explore and investigate new solutions for isolating and securely protecting tenants from one another in a multi-tenant OpenStack Cloud-SDN-NFV integrated platform.', N'~/Resources/projectpool/5e70f72d-5e6e-43ab-b359-8df94dd5fd92-doanhoangproject.p.pdf', 2, CAST(N'2018-03-24T22:47:11.000' AS DateTime), CAST(N'2018-03-31T12:19:39.477' AS DateTime), 87, N'Strong programming skills, problem solving ability, computer networking and cloud computing knowledge, and security fundamental understanding.')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (29, N'Design of smart Sydney city ', N'This project aims to explore the state-of-the-art technology and services available to develop smart cities and develop a conceptual design of smart Sydney city, including the key areas such as smart home, smart transformation and smart grid. You can start from learning services provided by the CMG (http://www.512cmg.com/). ', NULL, 3, CAST(N'2018-03-25T21:56:45.000' AS DateTime), CAST(N'2018-03-25T21:56:45.000' AS DateTime), 2, N'good reading, analysis and design skills.')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (30, N'Visualisation of privacy policies of social networks for young users', N'This projects aims to develop a  new way of visualising the privacy policies of popular social networks for young users.', NULL, 3, CAST(N'2018-03-25T23:54:21.000' AS DateTime), CAST(N'2018-03-25T23:54:21.000' AS DateTime), 2, N'Good reading and design skills and reasonable web system development skill.')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (31, N'sample project', N'sample project', NULL, 7, CAST(N'2018-03-26T00:15:04.000' AS DateTime), CAST(N'2018-03-26T00:15:04.000' AS DateTime), 23, N'sample project')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (32, N'Classification/Regression in Data Streams', N'Ever increasing IOT devices, user held devices, connected home appliances and apps have led to exponential growth in the data available for learning. The learning algorithms have to solve the classification or regression use cases using these streams of data differently than traditional batch data. 
Some of the examples are real-time recommendation/classification of electricity utilization using electric meter streaming data, monitoring patient’s condition and predicting a potential threat before it happens, wear and tear of large machines like turbines using smart sensors and predicting time for replacement, real-time analysis of news and stock markets. 
This project aims to conduct experiment with MoA platform using data streams, implement in Python and integrate the selected algorithms with the platform with Python, and compare the results. 
', N'~/Resources/projectpool/57b58657-67ec-48c2-971d-cadcfc1a4916-projectdetails-da.docx', 3, CAST(N'2018-03-26T04:51:32.000' AS DateTime), CAST(N'2018-03-26T04:51:32.000' AS DateTime), 65, N'Programming - Python and Java')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (33, N'Social Media Analysis – Extremism Behaviour in Jordanian Twitter Networks', N'The main goal of the study is to determine the propensity in the Jordanian general population towards violent extremism (VE) behaviour and support of that behaviour. 
In order to achieve that goal the online behaviour of Twitter users from Jordan is analysed. This is done using online data obtained from online social systems.
1. The opinions shared online by people (their tweets) are gathered and analysed (text analysis) to determine the attitude of a given person towards VE. Each user is assigned an attribute describing their attitude towards VE (VE score).
2. Based on the similar behaviour between users (e.g. using similar keyword) a social network is created.
3. The analysis of social network is performed in order to establish characteristics of each user and each class of users in the network (classes are assigned based on the V E score). This will help to understand the structure of the Jordanian population (at least the part that uses online services) and their attitude to V E.
All performed analyses enabled the determination of to what extent users are interested in V E, the structure of their relationships and how fast the V E behaviour can spread in the online community.', NULL, 2, CAST(N'2018-03-27T10:40:52.000' AS DateTime), CAST(N'2018-04-03T11:00:04.483' AS DateTime), 63, N'programming skills, critical analysis of existing literature, social network analytics - basics')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (34, N'Results of Eurovision song contest as a proxy to describe  socioeconomic relationships', N'Eurovision song contest is an event that brings 42 nations together. Although, the main goal of the contest is the entertainment and prestige for high-scoring countries, nowadays, it also gives an opportunity to analyze socio-economic relationships between countries. 
Also, since 2016, when the voting system changed, so we can see separately jury and public votes, the data are even more insightful, giving the opportunity to look at such phenomena as biases in public and jury voted, including regional likes/dislikes, stereotypes, or influence of immigration on the results.
', NULL, 3, CAST(N'2018-03-27T10:47:06.000' AS DateTime), CAST(N'2018-03-27T10:47:06.000' AS DateTime), 63, N'data analytics, some programming skills')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (35, N'Dynamics and Control of Complex Social Networks – Gender studies for equality – improving gender balance in creative industries', N'Gender studies for equality – improving gender balance in creative industries. The results of the conducted fundamental research will be used to improve the appalling long term statistics (last 30 years) describing the inequitable conditions for women in film industries. This will be achieved by applying developed control mechanisms to alter current collaboration network in the film industry. By modelling different what-if scenarios, the impact on the current network will be assessed and this will inform policy makers. The data to be used comes from film industry from Germany, Sweden, and Australia.

', NULL, 3, CAST(N'2018-03-27T10:48:23.000' AS DateTime), CAST(N'2018-03-27T10:48:23.000' AS DateTime), 63, N'data analytics, some programming skills')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (36, N'Detection of personality traits using physiological signals (in collaboration with Data 61)', N'Personality questionnaires backed by psychology theories have long been used to classify people into broad psychological groups. This project explores the feasibility to determine a person''s personality through observing their physiological and behavioural responses to external stimuli. Capturing physiological signals such as pupil dilation, skin conductance, or brain activity, while performing specific tasks, watching multimedia content, or playing a computer game may produce an accurate picture of personality. The project will involve experiment design and conduct, data collection, and analysis using machine learning techniques. The successful candidate for this project will work with CSIRO researchers in Data61 at the Australian Technology Park in Sydney, who have expertise in human-computer interaction, machine learning and psychology.', NULL, 2, CAST(N'2018-03-27T10:49:30.000' AS DateTime), CAST(N'2018-04-03T12:05:41.353' AS DateTime), 63, N'data analytics, programming skills')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (37, N' A decision support system for deciding on interested features in new product development', N'In current competitive times, product manufacturers need not only to retain their existing customer base, but also to increase their market share. One way they can achieve this is by generating new ideas and developing novel products with them. However, not all the generated ideas can be incorporated to the next version of the product. Hence, a decision support system is required to assist the product designers in selecting the best ideas from the generated ones while considering the company’s different objectives.', N'~/Resources/projectpool/49ff34b0-303e-4450-a687-7b9d214dab9c', 3, CAST(N'2018-03-29T07:47:47.000' AS DateTime), CAST(N'2018-03-29T07:47:47.000' AS DateTime), 116, N'Java/Python/ User Interface Development/ Fuzzy logic')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (39, N'Detection of personality traits using physiological signals (in collaboration with Data 61), No. 2', N'Personality questionnaires backed by psychology theories have long been used to classify people into broad psychological groups. This project explores the feasibility to determine a person''s personality through observing their physiological and behavioural responses to external stimuli. Capturing physiological signals such as pupil dilation, skin conductance, or brain activity, while performing specific tasks, watching multimedia content, or playing a computer game may produce an accurate picture of personality. The project will involve experiment design and conduct, data collection, and analysis using machine learning techniques. The successful candidate for this project will work with CSIRO researchers in Data61 at the Australian Technology Park in Sydney, who have expertise in human-computer interaction, machine learning and psychology.', NULL, 2, CAST(N'2018-04-03T12:11:57.000' AS DateTime), CAST(N'2018-04-03T12:11:57.000' AS DateTime), 63, N'data analysis, personality prediction')
INSERT [dbo].[ProjectPool] ([ID], [Title], [Description], [DocumentURL], [GroupSize], [CreatedAt], [UpdatedAt], [SupervisorID], [SkillsRequest]) VALUES (40, N'Representation of semantic data in the UTS Data Arena', N'This project aims at the dynamic and interactive representation of semantic data in the UTS Data Arena.
 
The student(s) will work mainly on Open Knowledge Graphs (OKGs) as a simple, yet important, class of ontology; therefore, the focus will be mainly on the Linked Data model. 
OKGs support a sort of "lightweight semantics" by providing, in a machine-readable standard format (e.g. RDF), a means for information. The resulting knowledge base can be collected and processed by standard software components, as well as can be linked to other ontologies or linked datasets. 

The student(s) is expected to:
(i) explore different options for the visualisation of large OKGs in the Data Arena; 
(ii) propose and implement a domain agnostic technique for such a purpose;  
(iii) develop a demonstrator based on a relevant study case.', NULL, 2, CAST(N'2018-05-24T05:16:55.000' AS DateTime), CAST(N'2018-05-24T05:42:57.590' AS DateTime), 130, N'Programming (Java, Python or equivalent)')
SET IDENTITY_INSERT [dbo].[ProjectPool] OFF
