/*
   Step 3:

	 Add the Keywords in table Keyword

*/

 
SET IDENTITY_INSERT [dbo].[Keyword] ON 

INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (1, N'Active Learning', N'Active learning is a special case of semi-supervised machine learning in which a learning algorithm is able to interactively query the user (or some other information source) to obtain the desired outputs at new data points.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (2, N'Artificial Intelligence In Games', N'AI in computer games', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (3, N'Artifitial Intelligence', N'Artificial intelligence (AI, also machine intelligence, MI) is intelligence demonstrated by machines, in contrast to the natural intelligence (NI) displayed by humans and other animals. In computer science AI research is defined as the study of "intelligent agents": any device that perceives its environment and takes actions that maximize its chance of successfully achieving its goals.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (4, N'Bayesian Network', N'A Bayesian network, Bayes network, belief network, Bayes(ian) model or probabilistic directed acyclic graphical model is a probabilistic graphical model (a type of statistical model) that represents a set of variables and their conditional dependencies via a directed acyclic graph (DAG).', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-03-25T22:55:40.727' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (5, N'Bayesian Analysis', N'Bayesian analysis is a statistical procedure which endeavors to estimate parameters of an underlying distribution based on the observed distribution. ', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (6, N'Bayesian Inference', N'Bayesian inference is a method of statistical inference in which Bayes theorem is used to update the probability for a hypothesis as more evidence or informationbecomes available. Bayesian inference is an important technique in statistics, and especially in mathematical statistics.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (7, N'Big Data', N'Big data is a term for data sets that are so large or complex that traditional data processing application software is inadequate to deal with them.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (8, N'Bioinformatics', N'Bioinformatics is an interdisciplinary field that develops methods and software tools for understanding biological data. ', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (9, N'Blockchain', N'A blockchain, originally block chain, is a continuously growing list of records, called blocks, which are linked and secured using cryptography. Each block typically contains a cryptographic hash of the previous block, a timestamp and transaction data.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (10, N'Causal Reasoning', N'Causal reasoning is the process of identifying causality: the relationship between a cause and its effect. ', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (11, N'Cloud Computing', N'The practice of using a network of remote servers hosted on the Internet to store, manage, and process data. It is on-demand delivery of IT resources and applications via the Internet with pay-as-you-go pricing.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (12, N'Collision Avoidance', N'Collision avoidance is the maintenance of systems and practices designed to prevent vehicles such as cars, trains, ships, and airplanes from colliding with other vehicles. ', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (13, N'Computer Animation', N'Computer animation is the process used for generating animated images. The more general term computer-generated imagery (CGI) encompasses both static scenes and dynamic images, while computer animation only refers to the moving images.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (14, N'Computer Game Development', N'Research topic related to video/computer games, effects, influence of computer games.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (15, N'Computer Games', N'PC games, also known as computer games or personal computer games, are video games played on a personal computer rather than a dedicated video game console or arcade machine. Their defining characteristics include a more diverse and user determined gaming hardware and software, and a generally greater capacity in input, processing, and video output.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (16, N'Computer Graphics', N'Computer graphics are pictures and films created using computers. Usually, the term refers to computer-generated image data created with help from specialized graphical hardware and software.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (17, N'Concept Drift', N'In predictive analytics and machine learning, the concept drift means that the statistical properties of the target variable, which the model is trying to predict, change over time in unforeseen ways. This causes problems because the predictions become less accurate as time passes.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (18, N'Culture in Information Systems', N'Culture impacts on design of Information systems, online communication, complex systems, social networking etc.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (19, N'Data Analytics', N'Data analytics (DA) is the process of examining data sets in order to draw conclusions about the information they contain, increasingly with the aid of specialized systems and software.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (20, N'Data Mining', N'Data mining is the computing process of discovering patterns in large data sets involving methods at the intersection of machine learning, statistics, and database systems.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (21, N'Data Transmission', N'Data transmission also data communication or digital communications is the transfer of data (a digital bitstream or a digitized analog signal) over a point-to-point or point-to-multipoint communicationchannel. ', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (22, N'Data Visualization', N'It involves the creation and study of the visual representation of data. A primary goal of data visualization is to communicate information clearly and efficiently via statistical graphics, plots and information graphics.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (23, N'Database Management', N'A database-management system (DBMS) is a computer-software application that interacts with end-users, other applications, and the database itself to capture and analyze data. A general-purpose DBMS allows the definition, creation, querying, update, and administration of databases.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (24, N'Digital Image Processing', N'Digital image processing is the use of computer algorithms to perform image processing on digital images.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (25, N'DNA', N'DNA profiling (also called DNA fingerprinting, DNA testing, or DNA typing) is a forensic technique used to identify individuals by characteristics of their DNA', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (26, N'E-Government', N'E-Government (short for electronic government) is the use of electronic communications devices, computers and the Internet to provide public services to citizens and other persons in a country or region. ', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (27, N'Evolutionary Algorithm', N'In artificial intelligence, an evolutionary algorithm (EA) is a generic population-based metaheuristic optimization algorithm.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (28, N'Expert Systems', N'In artificial intelligence, an expert system is a computer system that emulates the decision-making ability of a human expert.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (29, N'Fuzzy Logic', N'Fuzzy logic is a form of many-valued logic in which the truth values of variables may be any real number between 0 and 1. It is employed to handle the concept of partial truth, where the truth value may range between completely true and completely false.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (30, N'Game Theory', N'Game theory is "the study of mathematical models of conflict and cooperation between intelligent rational decision-makers". Game theory is mainly used in economics, political science, and psychology, as well as logic, computer science and biology.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (31, N'Genetic Algorithm', N'In computer science and operations research, a genetic algorithm (GA) is a metaheuristic inspired by the process of natural selection that belongs to the larger class of evolutionary algorithms (EA). Genetic algorithms are commonly used to generate high-quality solutions to optimization and search problems by relying on bio-inspired operators such as mutation, crossover and selection.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (32, N'Graph Theory', N'In mathematics, graph theory is the study of graphs, which are mathematical structures used to model pairwise relations between objects. A graph in this context is made up of vertices, nodes, or points which are connected by edges, arcs, or lines.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (33, N'Health Informatics', N'Health informatics is informatics in health care, essentially the management and use of patient healthcare information. It is a multidisciplinary field that uses health information technology (HIT) to improve health care via any combination of higher quality, higher efficiency and new opportunities. ', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (34, N'Human-Computer Interaction', N'Human¨Ccomputer interaction (commonly referred to as HCI) researches the design and use of computer technology, focused on the interfaces between people (users) and computers. Researchers in the field of HCI both observe the ways in which humans interact with computers and design technologies that let humans interact with computers in novel ways. As a field of research, human-computer interaction is situated at the intersection of computer science, behavioral sciences, design, media studies, and several other fields of study.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (35, N'Information and Quantum Information Theory', N'All aspects of Shannon theory and for classical and quantum-mechanical systems', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (36, N'Information Communications technology', N'Information and communication technology (ICT) is an another/extensional term for information technology (IT) which stresses the role of unified communications and the integration of telecommunications (telephone lines and wireless signals), computers as well as necessary enterprise software, middleware, storage, and audio-visual systems, which enable users to access, store, transmit, and manipulate information.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (37, N'Information Retrieval', N'Information retrieval (IR) is the activity of obtaining information resources relevant to an information need from a collection of information resources. ', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (38, N'Intelligent Agents', N'In artificial intelligence, an intelligent agent (IA) is an autonomous entity which observes through sensors and acts upon an environment using actuators (i.e. it is an agent) and directs its activity towards achieving goals.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (39, N'Internet of Things (IOT) ', N'the interconnection via the Internet of computing devices embedded in everyday objects, enabling them to send and receive data.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (40, N'Knowledge Base', N'It is a technology used to store complex structured and unstructured information used by a computer system', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (41, N'Knowledge Representation', N'It aims at representing information about the world in a form that a computer system can utilize ', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (42, N'Machine Learning', N'Machine learning explores the study and construction of algorithms that can learn from and make predictions on data[3] ¨C such algorithms overcome following strictly static program instructions by making data-driven predictions or decisions,[4]:2 through building a model from sample inputs.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (43, N'Mixed-Reality', N'Mixed reality (MR), sometimes referred to as hybrid reality,[1] is the merging of real and virtual worlds to produce new environments and visualizations where physical and digital objects co-exist and interact in real time.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (44, N'Mobile Technologies', N'Mobile technology is the technology used for cellular communication.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (45, N'Multimedia', N'Digital contents that includes video, animation and interactive media.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (46, N'Ontology', N'A set of concepts in a subject area or domain that shows their properties and the relations between them.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (47, N'Path Finding', N'Pathfinding or pathing is the plotting, by a computer application, of the shortest route between two points. It is a more practical variant on solving mazes. This field of research is based heavily on Dijkstras algorithm for finding a shortest path on a weighted graph.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (48, N'Pattern Recognition', N'Pattern recognition is a branch of machine learning that focuses on the recognition of patterns and regularities in data, although it is in some cases considered to be nearly synonymous with machine learning.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (49, N'Raspberry Pi', N'The Raspberry Pi is a series of small single-board computers developed in the United Kingdom by the Raspberry Pi Foundation to promote the teaching of basic computer science in schools and in developing countries.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (50, N'Recommendation Systems', N'A recommender system or a recommendation system is a subclass of information filtering system that seeks to predict the "rating" or "preference" that a user would give to an item', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (51, N'Robotics', N'Robotics is an interdisciplinary branch of engineering and science that includes mechanical engineering, electrical engineering, computer science, and others. Robotics deals with the design, construction, operation, and use of robots, as well as computer systems for their control, sensory feedback, and information processing.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (52, N'Situation Awareness', N'Situation Awareness is a field of study concerned with understanding of the environment critical to decision-makers in complex, dynamic areas from aviation, air traffic control, ship navigation, power plant operations, military command and control, and emergency services such as fire fighting and policing; to more ordinary but nevertheless complex tasks such as driving an automobile or riding a bicycle.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (53, N'Social Media', N'Social media are computer-mediated technologies that facilitate the creation and sharing of information, ideas, career interests and other forms of expression via virtual communities and networks. Examples are Facebook, Twitter, Tumblr and etc...', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (54, N'Software Engineering', N'Software Engineering is the application of engineering to the development of software in a systematic method', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (55, N'Time Series', N'A time series is a series of data points indexed (or listed or graphed) in time order. Most commonly, a time series is a sequence taken at successive equally spaced points in time. Thus it is a sequence of discrete-time data.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (56, N'Transfer Learning', N'Transfer learning or inductive transfer is a research problem in machine learning that focuses on storing knowledge gained while solving one problem and applying it to a different but related problem.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (57, N'Virtual Reality', N'Virtual reality (VR) is a computer-generated scenario that simulates a realistic experience. The immersive environment can be similar to the real world in order to create a lifelike experience grounded in reality or sci-fi.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (58, N'Web Search Engine', N'A software system that is designed to search for information on the World Wide Web.', CAST(N'2018-01-18T08:08:08.000' AS DateTime), CAST(N'2018-01-18T08:08:08.000' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (59, N'Cybersecurity', N'Cybersecurity, computer security or IT security is the protection of computer systems from the theft and damage to their hardware, software or information, as well as from disruption or misdirection of the services they provide.

Cybersecurity includes controlling physical access to the hardware, as well as protecting against harm that may come via network access, data and code injection.', CAST(N'2018-03-25T22:57:36.080' AS DateTime), CAST(N'2018-03-25T22:57:36.080' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (60, N'Resource optimization ', N'Resource optimization is the set of processes and methods to match the available resources (human, machinery, financial) with the needs of the organization in order to achieve established goals. 
"https://www.intelligentmanagement.ws/learningcentre/how-can-we-optimize-resources-and-processes/resource-optimization/"', CAST(N'2018-03-25T23:12:02.463' AS DateTime), CAST(N'2018-03-25T23:16:15.510' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (61, N'Information privacy', N'Information privacy, or data privacy (or data protection), is the relationship between the collection and dissemination of data, technology, the public expectation of privacy, and the legal and political issues surrounding them.

Privacy concerns exist wherever personally identifiable information or other sensitive information is collected, stored, used, and finally destroyed or deleted ¨C in digital form or otherwise.
"https://en.wikipedia.org/wiki/Information_privacy"', CAST(N'2018-03-26T00:01:56.340' AS DateTime), CAST(N'2018-03-26T00:01:56.340' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (62, N'data stream', N'A data stream is a sequence of digitally encoded coherent signals (packets of data or data packets) used to transmit or receive information that is in the process of being transmitted. "https://en.wikipedia.org/wiki/Data_stream"', CAST(N'2018-03-26T04:57:40.247' AS DateTime), CAST(N'2018-03-26T04:57:40.247' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (63, N'social network', N'A social network is a social structure made up of a set of social actors (such as individuals or organizations),  and social interactions between actors. The social network perspective provides a set of methods for analyzing the structure of whole social entities as well as a variety of theories explaining the patterns observed in these structures.
"https://en.wikipedia.org/wiki/Social_network"', CAST(N'2018-03-28T23:36:21.333' AS DateTime), CAST(N'2018-03-28T23:36:21.333' AS DateTime), 1)
INSERT [dbo].[Keyword] ([ID], [Title], [Description], [CreatedAt], [UpdatedAt], [CoordinatorID]) VALUES (64, N'social network analysis', N'Social network analysis (SNA) is the process of investigating social structures through the use of networks and graph theory. It characterizes networked structures in terms of nodes (individual actors, people, or things within the network) and the ties, edges, or links (relationships or interactions) that connect them. 
"https://en.wikipedia.org/wiki/Social_network_analysis"', CAST(N'2018-03-28T23:37:34.460' AS DateTime), CAST(N'2018-03-28T23:37:34.460' AS DateTime), 1)

SET IDENTITY_INSERT [dbo].[Keyword] OFF
